In [8]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer

df = pd.read_csv('student_mental_health_burnout.csv')

#Conhecendo os dados

display(df.head())
print(f'O df tem {df.shape[1]} Colunas e {df.shape[0]} Linhas')
print('\n')

df = df.drop(columns=['student_id']) # retirando a coluna de id

#Percebe-se que algumas colunas como gender, stress_level, sleep_quality podem ser normalizadas por
#terem valores que são poucas classificações.

#Irei separar algumas colunas do tipo para analisá-las

colunas_analise = ['gender', 'course', 'year', 'stress_level', 'sleep_quality', 'internet_quality', 'burnout_level']

# como temos 3 colunas que são classificações / sem ordem, temos que ter um tratamento diferente com elas

colunas_ordinais = ['stress_level', 'sleep_quality', 'internet_quality', 'burnout_level']
colunas_str = ['gender', 'course', 'year']

for coluna in colunas_analise:

    print(f'Feature : {coluna}')
    print(f'Número de Valores possíveis: {df[coluna].unique()}')
    print('\n')

#Como previsto, algumas colunas podem ser padronizadas
#Como os valores são strings e não há valores fora do padrão, nãos será necessário corrigir as strings.

   student_id  age  gender  ...  cgpa internet_quality  burnout_level
0      100001   23    Male  ...  9.63             Good           High
1      100002   20    Male  ...  6.04             Poor            Low
2      100003   24  Female  ...  8.31             Good           High
3      100004   21    Male  ...  5.95             Good           High
4      100005   23   Other  ...  8.51             Good            Low

[5 rows x 20 columns]

O df tem 20 Colunas e 150000 Linhas


Feature : gender
Número de Valores possíveis: <StringArray>
['Male', 'Female', 'Other']
Length: 3, dtype: str


Feature : course
Número de Valores possíveis: <StringArray>
['BTech', 'BCA', 'BSc', 'MBA', 'MCA', 'BBA']
Length: 6, dtype: str


Feature : year
Número de Valores possíveis: <StringArray>
['1st', '3rd', '4th', '2nd']
Length: 4, dtype: str


Feature : stress_level
Número de Valores possíveis: <StringArray>
['High', 'Low', 'Medium']
Length: 3, dtype: str


Feature : sleep_quality
Número de Valores possíveis: <StringArray>
['Average', 'Poor', 'Good']
Length: 3, dtype: str


Feature : internet_quality
Número de Valores possíveis: <StringArray>
['Good', 'Poor', 'Average']
Length: 3, dtype: str


Feature : burnout_level
Número de Valores possíveis: <StringArray>
['High', 'Low', 'Medium']
Length: 3, dtype: str

In [13]:
# Vou usar o ColumnTransformer com OneHotEncoder e OrdinalEncoder, para poder ter um mecanismo mais eficiente para
#tratar os dados

preprocessor = ColumnTransformer(transformers=[
    ('nao_ordinario', OneHotEncoder(drop='first'), colunas_str), #trata as colunas nao ordinais 
    ('ordinal', OrdinalEncoder(), colunas_ordinais) # trata as colunas ordinais
], remainder='passthrough')

novo_df = preprocessor.fit_transform(df) # Isso é uma matriz numpy!
novas_colunas = preprocessor.get_feature_names_out() # pega o nome das colunas pós transformação

print('Nome das novas colunas: ')
print(novas_colunas)
print('\n')

novo_df = pd.DataFrame(novo_df, columns=novas_colunas)

#Visualizando os dados tratados:

display(novo_df.head(30))
print('\n')

# Agora, podemos dividir o dataset e formar os dados e o target

y_data = novo_df['ordinal__burnout_level']
x_data = novo_df.drop(columns=['ordinal__burnout_level'])

print('Dados Gerais: ')
display(x_data)
print('\n')
print('Resultados: ')
print(y_data)

Nome das novas colunas:
['nao_ordinario__gender_Male' 'nao_ordinario__gender_Other'
 'nao_ordinario__course_BCA' 'nao_ordinario__course_BSc'
 'nao_ordinario__course_BTech' 'nao_ordinario__course_MBA'
 'nao_ordinario__course_MCA' 'nao_ordinario__year_2nd'
 'nao_ordinario__year_3rd' 'nao_ordinario__year_4th'
 'ordinal__stress_level' 'ordinal__sleep_quality'
 'ordinal__internet_quality' 'ordinal__burnout_level' 'remainder__age'
 'remainder__daily_study_hours' 'remainder__daily_sleep_hours'
 'remainder__screen_time_hours' 'remainder__anxiety_score'
 'remainder__depression_score' 'remainder__academic_pressure_score'
 'remainder__financial_stress_score' 'remainder__social_support_score'
 'remainder__physical_activity_hours' 'remainder__attendance_percentage'
 'remainder__cgpa']

    nao_ordinario__gender_Male  ...  remainder__cgpa
0                          1.0  ...             9.63
1                          1.0  ...             6.04
2                          0.0  ...             8.31
3                          1.0  ...             5.95
4                          0.0  ...             8.51
5                          1.0  ...             6.82
6                          0.0  ...             5.36
7                          1.0  ...             5.91
8                          1.0  ...             7.23
9                          1.0  ...             6.26
10                         0.0  ...             9.31
11                         0.0  ...             5.62
12                         1.0  ...             9.53
13                         0.0  ...             4.06
14                         0.0  ...             8.60
15                         0.0  ...             9.07
16                         1.0  ...             5.80
17                         0.0  ...             8.64
18                         1.0  ...             8.80
19                         0.0  ...             9.45
20                         1.0  ...             6.00
21                         0.0  ...             5.45
22                         1.0  ...             4.46
23                         0.0  ...             9.58
24                         1.0  ...             6.82
25                         1.0  ...             4.54
26                         0.0  ...             9.12
27                         0.0  ...             9.24
28                         1.0  ...             5.04
29                         0.0  ...             4.72

[30 rows x 26 columns]

Dados Gerais:

        nao_ordinario__gender_Male  ...  remainder__cgpa
0                              1.0  ...             9.63
1                              1.0  ...             6.04
2                              0.0  ...             8.31
3                              1.0  ...             5.95
4                              0.0  ...             8.51
...                            ...  ...              ...
149995                         0.0  ...             7.82
149996                         1.0  ...             7.19
149997                         1.0  ...             9.78
149998                         1.0  ...             9.88
149999                         1.0  ...             7.00

[150000 rows x 25 columns]

Resultados:
0         0.0
1         1.0
2         0.0
3         0.0
4         1.0
         ...
149995    1.0
149996    0.0
149997    0.0
149998    2.0
149999    0.0
Name: ordinal__burnout_level, Length: 150000, dtype: float64